version: '3.9'

x-env: &global-env
    NODE_SERVICE: &node-service node_service
    NODE_SERVICE_PORT: 3000

services:
    web:
        image: nginx:1.19.9
        container_name: nginx_server
        environment: *global-env
        volumes:
            - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/etc/nginx/templates:/etc/nginx/templates
            - ./nginx/etc/nginx/njs:/etc/nginx/njs
        ports:
            - '${PORT:-80}:80'

    node:
        image: node:latest
        container_name: *node-service
        environment: *global-env
        command: node /src/server
        volumes:
            - ./node/src:/src
